//
//  Samples.swift
//  UnsupervisedTextClassifier
//
//  Created by Javier Fuentes on 05-04-21.
//

import Foundation

let sampleHeadlines = ["How many people can I have a drink with? And other questions",
                       "Full interview: Hillary Clinton, January 17",
                       "Covid lockdown eases: Celebrations as pub gardens and shops reopen",
                       "Chauvin Trial Judge Denies Request For Jury Sequestration After Police Shooting",
                       "Psaki says Biden 'does not spend his time tweeting conspiracy theories' after a GOP senator criticized the president's social-media use",
                       "Police release bodycam footage from officer involved shooting in Minnesota",
                       "Ecuador Elects Conservative President, Saying 'Never Again' to Socialist Past",
                       "New antibody cocktail reduce symptomatic Covid infection by 81%, Regeneron says",
                       "Did Kris Jenner just send Jordyn Woods a personalized gift?",
                       "VIDEO: Men on Motorcycle Allegedly Snatch Woman's Necklace in NYC",
                       "'Skilled predator' FBI boss harassed 8 women, watchdog finds",
                       "Studies Confirm Racial, Ethnic Disparities In COVID-19 Hospitalizations And Visits",
                       "Georgia sheriff: 3 officers wounded, 1 suspect dead, 1 held",
                       "Analysis: Biden doesn't tweet enough wild stuff for this Republican",
                       "GOP Rep. Banks: Important to 'Cement' the Relationship Between Republicans, Working-Class Voters",
                       "David Hogg resigns from progressive MyPillow competitor",
                       "The hellish future of post-Covid travel &amp; a special tribute at the end of this show",
                       "Graphic bodycam video released of deadly police shooting in Minnesota",
                       "Daunte Wright Shooting an 'Accidental Discharge,' Brooklyn Center Police Chief Says",
                       "AstraZeneca vaccine: How do you weigh up the risks and benefits?",
                       "Haley says she'll back Trump, stand down if he runs in 2024",
                       "Dems' voting plan could make immigrants vulnerable to what experts call 'kiss of death'",
                       "Prince Philip on royal duty: In his own words",
                       "Greensill: Government to investigate Cameron's lobbying",
                       "As Locusts Swarmed East Africa, This Tech Helped Squash Them",
                       "'Dumb son of a bitch': Trump rips McConnell at Mar-a-Lago",
                       "Here's what happened today",
                       "A guide for Muslims observing Ramadan during the pandemic",
                       "U.S. Budget Deficit Widened to a Record $1.7 Trillion for First Half",
                       "Those We’ve Lost to the Coronavirus",
                       "Prince Philip: William and Harry pay tribute to grandfather",
                       "The Ghosts of Northern Ireland’s Troubles Are Back. What’s Going On?",
                       "What are the rules for weddings and can I hold a reception?",
                       "2-year-old shot in the head during gunfight in Newark",
                       "Joe Biden’s ‘War on Women’: Education Department Denies Request to Affirm Title IX Male/Female Sex",
                       "This Heroin-Using Professor Wants to Change How We Think About Drugs",
                       "Why India and Nepal's forest fires are worrying scientists",
                       "Cuomo’s Albany dominance takes backseat to political survival",
                       "Excessive Drinking Rose During the Pandemic. Here Are Ways to Cut Back.",
                       "A Push to Move the Golf Course Atop a Native American ‘Stonehenge’",
                       "Embattled Rep. Matt Gaetz is denied a meeting with Trump",
                       "Luxury Condo Boasts Floor-To-Ceiling Toilets",
                       "Twitter Censors Jason Whitlock's Post About BLM Co-Founder's Million Dollar Home",
                       "April Ryan: GOP Is an 'Anti-Browning Party' -- 'Does Not Like the Browning of America'",
                       "Macaulay Culkin and Brenda Song welcome their first child together",
                       "William and Harry pay tribute to Philip for his service to the U.K., queen — and BBQ",
                       "Wrestlemania wasn't just a good promo for Bad Bunny. It was also great for the WWE.",
                       "State Department says it's not considering joint boycott of 2022 Beijing Olympics",
                       "Israeli president picks Netanyahu to try to form government",
                       "'World's biggest rabbit' stolen from owner's garden",
                       "George Floyd's younger sibling tells court: 'I miss my brother'",
                       "MLB's Move Out Of Georgia Is The Latest In A Line Of Political Boycotts",
                       "Media 'hall monitor' Brian Stelter downplays '60 Minutes' DeSantis report 'missteps' on CNN show",
                       "Juan Williams: The GOP is now the party of grifters and kooks",
                       "Report: Huh, Interesting Choice For An Outfit Today",
                       "Who should stop dancing to be taken seriously? - Garth Crooks' team of the week",
                       "Egypt Refuses to Release Suez Canal-Blocking Ship Without 'Compensation'",
                       "WATCH: George Floyd's Brother Testifies In Derek Chauvin Trial",
                       "Covid damage leading to 'completely new category' of organ transplants",
                       "Ex-police chief gets 1 year in prison for hiring scandal",
                       "Sen. Wicker on infrastructure meeting with Biden: We made good points but 'there is a lot of space between us'",
                       "Former soldiers charged in stabbing death of another soldier",
                       "Daunte Wright, Michigan, Iran: Your Monday Evening Briefing",
                       "CDC Director Rochelle Walensky: Michigan Should 'Close Things Down' Amid Coronavirus Surge",
                       "The Crossword, Tiles and More",
                       "A Teacher Marched to the Capitol. When She Got Home, the Fight Began.",
                       "Will Experian Boost help your credit score? Here's what to know",
                       "Baseball's All-Star Game reportedly moving to Denver",
                       "Bernie Sanders: We can pull off “one of the great political upsets in modern history”",
                       "Get ready for the new Roaring '20s",
                       "People are moving to Duluth, Minnesota, for one particularly big reason",
                       "Rangers refuse to take shortcuts at NHL trade deadline",
                       "Scores of Californians are moving to Texas",
                       "Trey Lance is mystery man of 2021 NFL Draft: ‘A lot of questions’",
                       "Trump relaunches his fundraising machine after months of quiet",
                       "Ex-Kansas City Chiefs Assistant Coach Britt Reid Charged with DWI",
                       "Scandal Erupts in Valdosta, Georgia's Football ''Titletown''",
                       "‘Bond Girl’ Talk and Groping: Albany’s Toxic Culture for Women",
                       "Elephant calf rescued from bottom of well in India",
                       "Biden’s Quiet ‘Breakthrough’ In Talking About Race",
                       "Biden USCIS nominee called for pausing border patrol funding",
                       "Don't worry about coronavirus variants overpowering vaccines, experts say",
                       "Tiles",
                       "Stream It Or Skip It: ‘Stars Fell on Alabama’ On Hulu, A Rom-Com In The Style Of All Those Hallmark Christmas Movies",
                       "'I never get tired of this feeling' - Cavendish earns first win since 2018",
                       "‘My Friends and I Knew Every Neighbor, and They Knew Us’",
                       "Cardiologist testifies that George Floyd did not die from drug overdose",
                       "A former Minneapolis police officer said Derek Chauvin violated protocol kneeling on George Floyd's neck, but he doesn't think the officer committed a crime",
                       "The Point: Why Thursday explains America's gun debate",
                       "Head of Elite Catholic School Is Fired Over Sexual Misconduct Charges",
                       "Derek Chauvin trial live: George Floyd's brother testifies; judge won't sequester jury amid Brooklyn Center protests, Minneapolis curfew",
                       "Covid: The countries that nailed it, and what we can learn from them",
                       "CDC issues travel warning for pregnant women",
                       "LIVE:  ABC News Live",
                       "1/16: Iran and U.S. complete prisoner exchange, nuclear deal implemented; Baby panda makes first public appearance",
                       "This tricky creature isn’t a snake — or a worm, wildlife officials say. What is it?",
                       "How Leslie Caron rebelled against movie studio hairdressers",
                       "How To Deal With Common Dog Behavior Problems",
                       "Black Conservative Pastors Expose 5 Lies by Joe Biden, Stacey Abrams About Georgia Election Bill",
                       "California teachers’ latest demand: Free child care",
                       "All eyes are on Georgia. Again.",
                       "Prince Philip: Death of the Duke of Edinburgh announced",
                       "Biden Begins Infrastructure Negotiations Signaling Flexibility",
                       "Prince Philip was flawed. He was also family",
                       "Coronavirus: What are the rules for places of worship?",
                       "Rachael Blackmore: Historic Grand National triumph for modest trailblazer",
                       "Nevskaya Manufaktura: Fire destroys historic factory in St Petersburg",
                       "Lockdown rules: What are the restrictions in your area?",
                       "Patchwork: Atlanta Braves cover All-Star logo on jerseys, shift hats",
                       "A former Minneapolis police officer said he quit days before the Derek Chauvin trial because he thinks protesters will 'burn the city down' no matter the case's outcome",
                       "Opinion: As people flee climate change on the coasts, this Midwest city is trying to become a safe haven",
                       "Michigan woman sues official who showed rifle during meeting",
                       "‘Felt like a setup’: WhatsApp chat shows Gaetz ally scrambling to contain fallout",
                       "Biden’s Infrastructure Push Spurs a Flurry of Lobbying in Congress",
                       "Blake Bailey on Writing His Life of Philip Roth",
                       "Why is the EU unhappy with AstraZeneca?",
                       "Poll Finds Republicans Particularly Opposed To 'Vaccine Passport' Messaging",
                       "How guns are smuggled from state to state on the iron pipeline",
                       "Red Sox-Twins Game Postponed Following Fatal Police Shooting",
                       "NYC’s hottest new bar is a subway speakeasy with a 1,500-person waitlist",
                       "How F.D.R.’s Heir Is Changing the Country",
                       "3,000-year-old city discovered and looks like it was 'left as if it were yesterday'",
                       "Takeaways From Day 11 of the Chauvin Trial: George Floyd’s Brother Testifies",
                       "'Another horrific act of gun violence': One dead, officer injured in high school shooting in Knoxville, Tennessee",
                       "EXPLAINER: How does an officer use a gun instead of a Taser?",
                       "Huge gatherings at India's Hindu festival as virus surges",
                       "'Multiple Gunshot Victims' After Shooting at Tennessee High School",
                       "Nolte: Dreadful Decade of Best Picture Winners Marches on Into 2021",
                       "Donald Trump, Ted Cruz slam Iran prisoner deal",
                       "Harry releases eulogy for Prince Philip",
                       "Biden Announces Gun Control Executive Actions",
                       "Lachlan Murdoch dismisses ADL complaint, says Fox sees no problem with Tucker Carlson's 'replacement theory' remarks",
                       "Trump curses McConnell's name during rant at Republican donor event",
                       "Michigan officials beg for help as state becomes COVID epicenter",
                       "Will Smith's slavery film Emancipation pulls out of Georgia over voting laws",
                       "Marco Rubio: American hostages “are not prisoners”",
                       "Timeline Of Major Physics Discoveries",
                       "Republicans want to make 'woke' corporations pay — literally",
                       "Scott Yenor to Tucker Carlson: People find more happiness in marriage, family life than individualism",
                       "McGregor tells Poirier their trilogy fight in July is 'off'",
                       "Change In Mobile App’s Logo Completely Disrupts Muscle Memory",
                       "Covid and twins: 'Huge' impact of lockdown separation",
                       "Prince Philip: 99 years, 143 countries and one very famous wife",
                       "Andrew Yang’s Asian American Superpower",
                       "'It's thrilling, exciting and terrifying': NASA prepares for first helicopter flight on Mars",
                       "The Queen and Prince Philip: An enduring royal romance",
                       "Phillies’ revamped bullpen making all the difference: Sherman",
                       "Protests erupt after Black man killed by police in Minnesota",
                       "Nation’s Gimps Crawl On Washington Demanding Unfair Treatment",
                       "Prince Philip: How can Prince Harry attend the funeral?",
                       "Covid-19 in the UK: How many coronavirus cases are there in your area?",
                       "2021 Masters Offers Brief Respite To Viewers Who Barely Suffered From Pandemic",
                       "Stream It Or Skip It: ‘Pray, Obey, Kill’ On HBO, A Docuseries About A Murder In A Swedish Religious Sect",
                       "Pelosi trashes AOC, Squad in ‘child-like’ voice: book",
                       "Relief: ‘Monster Hunter Rise’ Includes A Dossier Of Each Monster’s Problematic Behavior So You Don’t Feel Bad When You Kill Them",
                       "When the Queen was snapped 'giggling' at Prince Philip",
                       "New York parent seeks OK to marry their own adult child",
                       "Parents, Stop Talking About the ‘Lost Year’",
                       "Harry pays tribute to 'cheeky' grandpa Prince Philip as he arrives in UK for funeral",
                       "China encourages citizens to report critics via new 'snitch hotline' ahead of 100th birthday",
                       "Tweaked COVID vaccines in testing aim to fend off variants",
                       "Covid: Surge testing in Wandsworth and Lambeth after South African variant cluster found",
                       "MLB moves All-Star Game from Georgia over new voting law",
                       "Baby panda makes first public appearance",
                       "Amazon Celebrates Union Defeat By Raising All Prices 150% Anyway",
                       "Devastated Woman Knows She’ll Never Be As Beautiful As Banff National Park",
                       "What’s on TV This Week: ‘Our Towns’ and ‘Beethoven in Beijing’",
                       "What to Know About the Killing of Daunte Wright",
                       "Female officer 'accidentally' shot, killed driver during traffic stop: Police chief",
                       "Cop who pepper sprayed Army Lt. during traffic stop fired",
                       "Will Smith's Production Pulls Film Out of Georgia, Citing Voting Laws",
                       "Taliban backs out of Afghan peace conference in Istanbul",
                       "The judge in the Chauvin trial won't admit statements from Morries Hall, the passenger in George Floyd's car",
                       "Scandal-plagued Florida politician Joel Greenberg reportedly tried to leverage his relationship with Rep. Matt Gaetz to get a pardon from Trump",
                       "Vatican same-sex ruling dismays some Catholics",
                       "Prince Philip: The Vanuatu tribes mourning the death of their 'god'",
                       "Financial Corruption Plagues House Democrats as Republicans Find Success in Push to Ditch Corporations",
                       "Boehner says 'unemployed' Trump 'has nothing else to do' but 'cause trouble'",
                       "Score up to 100k bonus points with these Amex cards",
                       "Save big on the ultimate crafting tools from Cricut",
                       "China's Message to America: We're an Equal Now",
                       "Colorado Temporarily Re-Bans Marijuana For Statewide Tolerance Break",
                       "Tom Cotton Introduces Bill to Make States That Send Cash to Illegal Aliens Ineligible for Federal Funds",
                       "Blaming Israel, Iran Vows Revenge for Blackout at Nuclear Site",
                       "Gyles Brandreth: 'Prince Philip would have been touched by public reaction'",
                       "Don’t Mistake Silent Endurance for Resilience",
                       "Political Briefing: The politics of cancel culture",
                       "Shooting Death of Daunte Wright Sparks Looting, Destruction of Minnesota Businesses",
                       "Vet-approved collars and leashes that will make walking your dog so much easier",
                       "Full interview: Marco Rubio, January 17",
                       "VIDEO: Lightning Strike Shatters Tree Outside Wisconsin High School",
                       "Biden: 'Prepared to negotiate,' on infrastructure",
                       "The Telling of DMX’s Life Story",
                       "Politically Sound: What Schoolhouse Rock didn't teach you",
                       "Head's up: The IRS can tax bitcoin and other cryptocurrencies",
                       "Microsoft to Buy Speech-Recognition Firm Nuance",
                       "A legal expert explains what it would take for police to get involved in the James Charles sexting scandal",
                       "13 beginner-friendly indoor plants you'll want to buy this spring",
                       "WH: Can't play 'whac-a-mole' with vaccine supply",
                       "Covid vaccines: How fast is progress around the world?",
                       "Covid: 'I'm very happy to have my hairdresser back'",
                       "Yuri Gagarin: Sixty years since the first man went into space",
                       "Police Say 'Accidental Discharge' Of Gun Led To Daunte Wright's Death",
                       "Myanmar's military is charging families $85 to retrieve the bodies of relatives killed by its own forces",
                       "'Demonic Chihuahua hellscape': Meet Prancer, the puppy everyone wants after a brutally honest Facebook post",
                       "Police Officer Stabbed During Attempted Traffic Stop in New York",
                       "Hugh Jackman celebrates 25th wedding anniversary with Deborra-Lee Furness",
                       "Blinken names State Department's chief diversity and inclusion officer",
                       "Primark: Norwich shoppers undeterred by long queue",
                       "Cuomo at fault for elderly, minorities lagging behind in COVID vaccinations",
                       "How did it become normal for every police shooting to bring ruinous rioting?",
                       "Reporter from The Trace Claims People 'Snap' Ghost Guns Together 'Within Minutes'",
                       "The Other Reason the Labor Force Is Shrunken: Fear of Covid-19",
                       "Baroness Shirley Williams: Former cabinet minister dies aged 90",
                       "GOP Memo: Joe Biden Has Opened Borders to Help Donors and CEOs",
                       "Panthers Adopt Patchy-Haired, Shivering Rescue QB Who Spent Years Abused By Jets",
                       "‘They thank me’: Jerry Falwell Jr. says Liberty community still embraces him",
                       "What a photo of Trump’s new office reveals about how he wants to be remembered",
                       "Expert: Floyd would be alive if not for restraint",
                       "We tested 10 single-serve coffee makers: These 3 won us over",
                       "Poll Finds Americans Hate Being Trapped In Mazes",
                       "Vice Removes Article Featuring Photos of Genocide Victims Altered to Add Smiles",
                       "IBM spinoff joins a long list of questionable corporate names",
                       "Floyd's Death 'Absolutely Preventable,' Doctor Says In Chauvin Trial",
                       "White House Convenes Summit To Address Supply Shortage Crippling Auto Plants",
                       "Newspaper headlines: Brothers' tributes and Cameron 'welcomes' inquiry",
                       "Republican candidates feuding on all fronts",
                       "Shirley Williams: Pioneer who tried to reshape politics",
                       "Fallen K-9 cop honored by hundreds",
                       "Iran and U.S. complete prisoner exchange, nuclear deal implemented",
                       "Dem Rep. Kildee: I Sought Treatment for PTSD After Jan. 6 Riot",
                       "What's the roadmap for lifting lockdown?",
                       "Camille Pissarro: Transatlantic struggle for painting stolen by Nazis",
                       "Fauci Warns of 'Breakthrough' Infections: 'No Vaccine Is 100% Efficacious or Effective'",
                       "French Wine Production Ravaged by a Devastating Frost",
                       "Biden urges CEOs to 'step up' game on supply chain",
                       "Ant Group Announces Overhaul as China Tightens Its Grip",
                       "French Firms Reach $15.5 Billion Deal to Create Water, Waste Behemoth",
                       "Axe Files: Former MLB commissioner Bud Selig",
                       "Derek Chauvin trial: A role model. A mamma's boy. A football player. Younger brother recalls George Floyd for jurors",
                       "My Job and I: Is This a Love Letter?",
                       "Judge orders Nebraska to transport prisoner for abortion",
                       "Americans roll up sleeves for variant vaccine",
                       "How should investors react to New Year's sell-off on Wall Street?",
                       "Open: This is Face the Nation, January 17",
                       "The Tax Filing Deadline Was Delayed to May 17. Here's What to Know.",
                       "'MacGyver' fans campaign to save show",
                       "A Picture Book About Children At The Border Aims To Spark Family Conversations",
                       "Michigan's Covid-19 crisis could be a sign of what's to come for the US, expert says",
                       "French Police Hunting International Lego Thieves",
                       "Boeing Shareholders Will Weigh Need for More Changes to Board",
                       "The judge in the Derek Chauvin case is orchestrating one of the nation's most widely watched murder trials. Meet Peter Cahill.",
                       "Report: China Intensifies Crackdown on Christian House Churches",
                       "After Enduring World’s Longest Restrictions, Britain Begins to Unlock",
                       "Police: 1 dead, officer wounded in Tennessee school shooting",
                       "Raúl Castro is slated to step down from the Communist Party. Is Cuba in for a change?",
                       "Coronavirus: Your tributes to those who have died",
                       "Marco Rubio: I’m the only candidate that can unite the Republican party",
                       "1 killed and officer wounded in Tennessee high school shooting",
                       "Kerry addresses Iran nuclear deal, prisoner exchange",
                       "Video shows Black player forced to sit near banana peels",
                       "US economy is at an 'inflection point,' Fed chair says",
                       "Rare blood clots - what you need to know",
                       "Jeb Bush talks term limits with New Hampshire fan",
                       "Avlon: Marjorie Taylor Greene shows that crazy has a constituency",
                       "Is NY ready for a pro-Trump governor?",
                       "Kati Kariko Helped Shield the World From the Coronavirus",
                       "What are the UK plans for Covid passports?",
                       "Jordan says it foiled 'malicious plot' by former crown prince",
                       "You’ve Heard About Gerrymandering. What Happens When It Involves Prisons?",
                       "Shooting at a Tennessee High School Leaves One Dead and Officer Wounded",
                       "Water-worried Vegas wants useless grass a thing of the past",
                       "Regeneron Drug Stops Symptomatic Covid-19 in Study",
                       "President Obama declares emergency in Flint water crisis",
                       "Covid: What's happened to crime during the pandemic?",
                       "Ana de Armas steps out with buff mystery man in Los Angeles",
                       "Ohio police investigating after deadly emergency room shooting",
                       "Minnesota police say Daunte Wright shooting was due to 'accidental discharge'",
                       "Cybersecurity Firm Darktrace Targets $4 Billion London IPO",
                       "What Joe Manchin gets exactly right",
                       "How Biden Can Free America From Its Zoning Straitjacket",
                       "Live updates from Derek Chauvin's murder trial",
                       "Guy Fieri helped raise $25 million for restaurant workers",
                       "China Official Acknowledges Low Effectiveness of the Country's Covid Vaccines",
                       "Citing grave threat, Scientific American replaces 'climate change' with 'climate emergency'",
                       "Entirety Of Objectionable Human Behavior Explained To Toddler As Person Acting Silly",
                       "Can the Meritocracy Find God?",
                       "Egypt prosecutors find gross negligence behind train crash",
                       "Woman Gives Birth To ‘Super Twins’ Conceived Weeks Apart",
                       "Coronavirus: What are the rules for face masks or face coverings?",
                       "With Economy Poised for Best Growth Since '83, Inflation Lurks",
                       "34 Asian-owned brands you'll wish you'd known about sooner",
                       "Ukraine's President runs for cover on front line against Russia",
                       "The day in pictures",
                       "Lockdown easing: What to watch for when you’re out and about",
                       "'Back-to-back wins give West Brom hope and belief' - Allardyce",
                       "Pelosi Defends Biden Infrastructure Plan: 'The Most Expensive Maintenance Is No Maintenance'",
                       "How California's 'deeply flawed' vaccine rollout failed Latino and Black communities",
                       "Covid: How does the Oxford-AstraZeneca vaccine work?",
                       "'Huge' explosion rocks St. Vincent as volcano keeps erupting",
                       "1 dead and officer wounded in Knoxville school shooting",
                       "My Family’s Global Vaccine Journey",
                       "Pakistan police arrest radical Islamist party head in Lahore",
                       "Gyms re-opening: 'Everyone's raring to go - but take it slow'",
                       "MoneyWatch: Wall Street ends week with major sell-off; Holiday sales don't meet expectations",
                       "Analysis: Texas's governor doesn't seem to know what 'herd immunity' actually is",
                       "Corporate Leaders Discuss How to Address Georgia's Voting Laws",
                       "Prosecutors allege 13-year-old had a gun when he was shot by Chicago police: What we know",
                       "Aussie cake decorators hit the Big Apple",
                       "Eagles treated Doug Pederson ‘like a baby’ amid culture of paranoia",
                       "Prince Charles on Prince Philip: 'My family and I miss my father enormously'",
                       "A Chef’s Quest to Preserve Cambodia’s Lost Flavors",
                       "CA Teacher to Zoom Class: 'Sick to My Stomach' over Parents Telling Teachers 'How to Do Their Job'",
                       "The World’s 9 Most Expensive Listings Currently on the Market",
                       "Covid: How to get a test for coronavirus",
                       "Prince Philip tributes: 'I wanted my grandchildren to remember this day'",
                       "Extradition hearing to send Weinstein to LA delayed",
                       "With Warning to Democrats, Manchin Points the Way for Biden's Agenda",
                       "George Floyd's brother says he was a big mama's boy as prosecution nears the end of its case in Chauvin trial",
                       "GRAPHIC VIDEO: 'Possible Accidental Shooting' by Police of Minneapolis Man, Says Chief",
                       "Minnesota officer who shot Daunte Wright should have known difference between Taser, gun: Ted Williams",
                       "Sports move fixtures to avoid clash with Prince Philip funeral",
                       "How Tucker Carlson's 'great replacement' argument uses a new frame for an old fear",
                       "C.D.C. Director Says Michigan Should Shut Down to Slow Outbreak",
                       "Prancer, the 'demonic Chihuahua' everyone wants to adopt",
                       "Joe Biden Backtracks on Police Oversight Commission as Black Lives Matter Riots Erupt in Minnesota over Police Shooting",
                       "Texas Antitrust Lawsuit Claims Google Rigged Its Ad Exchange Against Competitors",
                       "Democrats face mounting hurdles to agenda",
                       "Nuclear agreement moves U.S.-Iran relations into new era",
                       "China official calls reports he said country's COVID-19 vaccines weren't very effective 'a complete misunderstanding'",
                       "Suspect arraigned in shooting at Missouri convenience store",
                       "Knoxville mayor says officer injured in school shooting is 'going to be OK'",
                       "Fauci talks about what he is comfortable doing now that he's fully vaccinated",
                       "Hear iconic cellist play for Anderson Cooper",
                       "14 Ways to Do Memphis Without Doing Memphis",
                       "Netanyahu to U.S. Defense Secretary Austin: Our Countries Won't Allow Iran to Obtain the Bomb",
                       "'Disturbing': Windsor, Virginia, police officer fired after using pepper spray at traffic stop",
                       "DeSantis attacks YouTube for yanking his pandemic video",
                       "Race report: Was controversy part of the plan?",
                       "The announcement of the death of Prince Philip",
                       "Spelling Bee",
                       "Camera position means VAR unable to reverse offside decision on West Brom 'goal'",
                       "The 'Iron Man' body armour many of us may soon be wearing",
                       "'This is murder': Outrage builds over death of Daunte Wright in traffic stop; police chief says officer intended to use Taser",
                       "Covid: Can my boss force me to go to work?",
                       "17-year-old killed after getting electrocuted by power line downed during severe weather",
                       "How ‘No Activity’ pivoted from live-action to animation",
                       "Reporters get heated with mayor and police chief",
                       "Love Island: Could Tinder find the show's first gay couple?",
                       "U.S. Army lieutenant files suit against two Virginia police officers for assault during traffic stop",
                       "Joseph Siravo, 'Sopranos' star, dies at 64",
                       "Covid: When will I get the vaccine?",
                       "Lebanon extends area claimed in border dispute with Israel",
                       "Biden picks 1st woman to be Army secretary",
                       "UN chief urges wealth tax of those who profited during COVID",
                       "Patriots' Julian Edelman retires; 'It's been the best 12 years of my life'",
                       "Religious Freedom Commissioners ‘Flattered’ by China’s Sanctions",
                       "Kentucky limits no-knock warrants after Breonna Taylor death",
                       "ShowBiz Minute: BAFTAs, Zhao, Prince Philip",
                       "Texas governor rejects first-pitch invite over MLB's All-Star snub",
                       "NASA: The latest in space exploration",
                       "Biden is reportedly vetting Cindy McCain for an ambassadorship in Rome",
                       "Brighton edge towards safety with draw against Everton",
                       "Remembering Alan Rickman",
                       "Obama unveils new unemployment insurance reforms",
                       "Jake Paul’s ‘World Series flasher’ ex-GF now training his nemesis",
                       "Prince Philip: A turbulent childhood stalked by exile, mental illness and death",
                       "Vertex",
                       "Ex-youth worker charged with rape was known for 'wrestling'",
                       "Coronavirus: What's happening with pools, haircuts and gyms?",
                       "Medical examiner blames police pressure for Floyd’s death",
                       "U.S. deficit hits $1.7 trillion over last six months",
                       "Family Awarded $29.5 Million After Actress Daughter Suffers Brain Damage from Pretzel",
                       "Iran nuclear attack: Mystery surrounds nuclear sabotage at Natanz",
                       "Republican Senators Question Whether Joe Biden Is 'Really in Charge' as Media Presence Is 'Unimaginably Conventional'",
                       "Watch These 11 Titles Before They Leave Netflix in April",
                       "George Floyd's brother breaks down as he testifies in Derek Chauvin trial",
                       "Steve Daines: 'Outrageous' States Handing Illegal Aliens Cash While Millions Unemployed",
                       "Covid: How are European countries tackling the pandemic?",
                       "Covid: What is the rule of six and what are the social distancing rules?",
                       "1 dead, officer injured after gunfire erupts at high school in Knoxville, Tennessee",
                       "Video shows runaway SUV doing donuts in reverse as driver tries to stop it on foot",
                       "'We found a baby on the subway - now he's our son'",
                       "PHOTO: Old Dog Tags Found Inside 445 Pound South Carolina Alligator's Belly",
                       "White Evangelicals’ Un-Christian Attacks on Raphael Warnock Attacks Say It All",
                       "Will Derek Chauvin take the stand in his murder trial in George Floyd's death? Your questions, answered",
                       "Moscow's palatial Yeliseyevsky food hall closes after 120 years",
                       "Psaki: WH saddened by latest Minneapolis shooting",
                       "California aims to 'fully reopen' economy by June 15",
                       "Daunte Wright shooting by police 'accidental'",
                       "‘Hurting’ Aaron Hicks sitting out Yankees game due to Daunte Wright shooting",
                       "Live Updates: Cop meant to draw Taser, not gun, before fatal shooting, police say",
                       "Tensions rise in water battle along Oregon-California line",
                       "Why Prince Philip Was Elusive Onscreen",
                       "Bloomberg alumni are back in action — and turning on their own",
                       "Several students from high school in Knoxville, Tennessee, fatally shot in prior incidents",
                       "New Mexico governor set to sign recreational marijuana bill",
                       "Listen to Episode 42 of ‘Amazin’ But True’: Is Luis Rojas in Over His Head? feat. Dwight Gooden",
                       "Would You Use An App To Verify Your Vaccine Status? The Idea Is Here To Stay",
                       "Rams officially return to Los Angeles",
                       "Every Covid-19 Death Leaves Behind a Circle of Grief",
                       "The Best Explanation of Biden’s Thinking I’ve Heard",
                       "Prince Philip: The Duke of Edinburgh's Award 'saved me from jail'",
                       "Los Angeles suburb demands answers for gas leak",
                       "Meet Atlas! Great Dane from Florida might be the world's tallest living dog",
                       "Know what's up before you finish your cup. Sign up to get the Daily Briefing.",
                       "Iran blames Israel for sabotage at Natanz nuclear site, vows revenge",
                       "Bodycam footage of Daunte Wright shooting released",
                       "The Country That Vaccinated 93% Of Adults In Under 2 Weeks",
                       "Harvey Weinstein learns about air fryers ahead of extradition hearing",
                       "Minnesota Police Say Officer Accidentally Discharged Weapon After Being Startled By Sight Of Gun In Own Hand",
                       "'That is obviously false': CNN reporter on Trump supporter's attempt to rewrite history",
                       "Covid: What’s the problem with the EU vaccine rollout?",
                       "Judge Asks If Chauvin Jury Minds Sticking Around For A Couple More Police Misconduct Trials",
                       "The real reason for GOP's attacks on transgender athletes",
                       "Jack Ma's Ant Group Bows to Beijing With Company Overhaul",
                       "Exclusive — Rep. Scott Perry: Biden ‘Infrastructure’ Plan Would Create ‘Soviet-Style’ American Economy",
                       "Shooting at Tennessee high school leaves 1 dead, police officer injured",
                       "Subpoenaing the Brookings Institution, Durham Focuses on Trump-Russia Dossier",
                       "Tucker Carlson and White Replacement",
                       "Gaetzgate is getting closer to Tallahassee and there are new odds on gambling reform",
                       "The leader of Sicily in Italy said as many as 80% of people are turning down the AstraZeneca jab",
                       "Speaker Ryan promises ''bold'' new GOP agenda",
                       "Antibody cocktail ‘rapidly’ prevents and treats COVID, study finds. Here’s how",
                       "Biden calls for peace and calm after MN shooting",
                       "Extended interview: Bernie Sanders, January 17",
                       "Sanders: Hillary Clinton “does not have a plan” for family medical leave",
                       "Philip tributes: 'A rock, a hero and one of a kind'",
                       "National Poetry Month: Coping With the Covid-19 Pandemic",
                       "Broadway vaccination site opens for NYC show staff",
                       "1 person dead, officer injured after shooting at a high school in Knoxville",
                       "Will Smith and Antoine Fuqua pull 'Emancipation' production from Georgia",
                       "'Shameless' series finale after-party hit a snag",
                       "Analysis: 100 days later, Brexit isn't working and business wants it fixed",
                       "SNL's 'Weekend Update' jokes it's nice to 'see women pay for an hour with Matt Gaetz,' hears out the Titanic's iceberg",
                       "Hackers want millions in ransom. American schools are considering the cost.",
                       "Democrats confront fragile majorities as Congress returns with big plans",
                       "Republicans Find a Cruel New Culture War: Transgender Rights",
                       "Oxford Street: Wooing shoppers back to Europe's busiest high street",
                       "Iran completes prisoner swap with U.S.",
                       "How Prince Philip's legacy could mend the rift with Harry and Meghan",
                       "US reacts to cyberattack on Iran's nuclear site",
                       "Food fight over GMOs",
                       "Democrats Used To Run From Big Government Label; They're Now Embracing It",
                       "Raw Materials Prices Have Surged. Corporate Profits Are Likely Next.",
                       "EV Startup Faraday's Road Back From the Brink Runs Through a SPAC",
                       "Anthony Fauci: 'We Very Well May Need' Coronavirus Booster Shots After 6-18 Months",
                       "Derek Chauvin trial: Prosecutors' case nears end as George Floyd's brother, use of force expert testify",
                       "Covid: The inside story of the government's battle against the virus",
                       "Duke Point Guard Reemerges With 5 Arms After Entering Interdimensional Transfer Portal",
                       "Covid-19: Debunking the latest wave of medical misinformation",
                       "The Iran Nuclear Talks, Explained",
                       "Pollak: Alleged Israel Attack on Iran's Natanz Facility Prevents Biden Capitulation",
                       "Rewards members: Score an extra 30% off with this Kohl's coupon",
                       "Virginia officer who pepper-sprayed Army officer fired",
                       "Trump blasts GOP leaders in sign he's too bitter to become president again",
                       "Minnesota officer meant to grab Taser before shooting Black man during traffic stop, police say",
                       "Domino's is launching a pizza delivery robot car",
                       "Europe’s Vaccination Problem",
                       "George Floyd's brother gives emotional testimony",
                       "The Friends reunion has been filmed in Los Angeles. Here's what we know",
                       "In pictures: Shoppers and gym-goers enjoy lockdown easing",
                       "A Public Health Lesson for Ron DeSantis, From Harvard",
                       "Police officer who pepper-sprayed US Army soldier fired",
                       "Kurds Warn Islamic State 'Back with a Vengeance' in Iraq",
                       "Biden offers measured response after viewing 'graphic' police footage of Daunte Wright's death",
                       "26 of the coolest home essentials at Amazon under $100",
                       "Cops went to a Florida mom’s home on a child abuse call. Then they saw a Dr. Seuss book",
                       "WATCH - Community Hosts 100 Car Parade for WWII Veteran's 100th Birthday: 'We Wanted to Honor Him'",
                       "Intel Introduces 'Bleep' AI to Censor Offensive Speech",
                       "BBC 'receives 100,000 complaints' over Prince Philip coverage",
                       "Where has the spring weather gone?",
                       "Letterbox contact: ‘Don’t my birth children have a right to know I’m dying?'",
                       "Fox stands behind Tucker Carlson after ADL urges his firing",
                       "Gov. John Kasich on Iran: “I’m sick to my stomach”",
                       "Black man killed by police during Minneapolis traffic stop, protests erupt",
                       "A Once-in-a-Century Crisis Can Help Educate Doctors",
                       "George Floyd's brother shed tears on witness stand",
                       "Huawei, HSBC Strike Deal Over Documents in Extradition Fight",
                       "Greensill: The questions still facing David Cameron",
                       "Protests break out in Minnesota after a Black man was shot by police during a traffic stop",
                       "Trump State Department appointee facing Capitol riot charges ordered released from jail",
                       "The best sales to shop today: Sony, Ulta, Echo and more",
                       "Covid vaccine: How many people in the UK have been vaccinated so far?",
                       "Boehner: Ted Cruz Is 'Lucifer in the Flesh'",
                       "Prince Philip vs Philip of 'The Crown': Fact and fiction",
                       "China Backtracks on Admission Its Coronavirus Vaccines Don't Work",
                       "Matt Gaetz associate Joel Greenberg has been accused of everything from acting as a vigilante police officer to trying to hack rival politicians",
                       "Republicans not pleased with Trump’s fiery Mar-a-Lago speech",
                       "Russia’s FM in Egypt for talks on ties and Ethiopia’s dam",
                       "5 Things To Know About Matt Gaetz",
                       "Bafta Film Awards 2021: Nomadland and Promising Young Woman win big",
                       "Curfew ordered for Minneapolis and St. Paul",
                       "Mom Accused of Fatally Stabbing 3 Kids Once Blogged About 'Teen Mom Stars' Being Bad Moms",
                       "NYC COVID cases tick down, as US infection rate rises",
                       "Germany Is Expected To Centralize Its COVID-19 Response. Some Fear It May Be Too Late",
                       "University of Central Florida Puts Players' Twitter Handles on Jerseys for Spring Game",
                       "Water companies illegally dumping sewage in England and Wales' rivers",
                       "England lockdown: Countdown to freedom",
                       "Minn. mom describes talking to son before shooting",
                       "Trump’s Corporate Tax Cut Was a Flop",
                       "Covid: When can I go on holiday abroad or in the UK?",
                       "Police officer who pepper-sprayed soldier in 'disturbing' traffic stop has been fired",
                       "'White Lives Matter' rallies flop as hardly anyone shows up",
                       "Jurors In Chauvin Trial Have Security Escort, Are Partially Sequestered",
                       "Obituary: HRH The Prince Philip, Duke of Edinburgh",
                       "From a South African Slur to a Scathing Drama About Toxic Masculinity",
                       "Biden meets with bipartisan group of lawmakers on infrastructure",
                       "Nike wants to resell your (lightly) worn shoes",
                       "Biden calls for 'peace and calm' after Wright's shooting",
                       "Immune-boosting drug may help before lung cancer surgery",
                       "I Thought I Knew How to Succeed as an Asian in U.S. Politics. Boy, Was I Wrong.",
                       "Shocking killing renews tensions over police",
                       "A Black family's beach property in California was taken during the Jim Crow era. The county is now giving it back, and it's worth millions",
                       "The 30% who could end the pandemic",
                       "Fauci says he would not hesitate to eat outdoors or go to a baseball game",
                       "Almanac: Mack Sennett",
                       "Matt Gaetz Is Both Unique and … Not So Unique",
                       "Bernie Sanders: Donald Trump is telling pathological lies to the American public",
                       "Unemployment rate: How many people are out of work?",
                       "Levi's CFO Plans to Increase Capital Spending on Digital Initiatives",
                       "American prisoners on their way home from Iran",
                       "Nikki Haley says if Trump runs for president in 2024 then she won't",
                       "Hillary Clinton calls on Bernie Sanders to change the Charleston loophole on guns",
                       "Prince Philip: Matt Smith and Tobias Menzies on playing the duke in The Crown",
                       "Vaccine hesitancy among Black Americans has turned a corner. Here's why.",
                       "Cadet Studying For Police Academy Exam Just Skimming Over Deescalation Training He’ll Never Use In Real Life",
                       "These $60 earbuds rival the AirPods in many ways",
                       "Police chief gets emotional during tense news conference",
                       "Man shot at his home two weeks ago killed in second shooting",
                       "TripAdvisor's top 25 all-inclusive resorts for your post-Covid trip",
                       "Vox Media to Buy Owner of Preet Bharara's Podcast",
                       "A federal judge was killed in a hit-and-run by a woman with the last name Snape who later yelled that she was Harry Potter, police say",
                       "Minnesota police chief describes the shooting of Daunte Wright as an 'accidental discharge' by the officer",
                       "Jen Psaki: Vaccine Outreach to White Conservatives Includes CMT and NASCAR",
                       "FL Supreme Court should slam Zilber for sexist, arrogant behavior unbecoming to a judge | Editorial",
                       "You Can Hear the Whistle Blow a Hundred Miles",
                       "Covid vaccine: All over-50s and high risk groups offered first dose",
                       "Being mixed race like Kamala Harris: 'I feel just as Indian as I feel black'",
                       "14-Year-Old Florida Boy Pulls Trapped Child Out of Overturned Car in Canal",
                       "Iran vows revenge against Israel for strike on Natanz nuclear plant",
                       "Bafta Film Awards 2021: Snobbery, pianos and other takeaways",
                       "Prime Cuts From Jenny Diski’s Catalog of Intimate, Witty Essays",
                       "WATCH: 'Trump was right, Biden is a Trojan horse for progressives'",
                       "Biden is likely to cut about $700 billion from his infrastructure plan in compromise, Goldman says",
                       "COMIC: How Your State Wins Or Loses Political Power Through The Census",
                       "Bafta Film Awards 2021: Red carpet in pictures",
                       "Pubs reopen in England: Gong marks the occasion",
                       "‘The Talk’ returns after Sharon Osbourne exit, Sheryl Underwood cites ‘PTSD’ following on-air spat",
                       "Grimes shows off the 'beautiful alien scars' she's had tattooed across her back",
                       "Dive Bar Opens After Pandemic To Find Grizzled Regular Still In Middle Of Story",
                       "Live Updates: 1 dead, 1 wounded in shooting at Tennessee high school",
                       "CDC says Michigan not likely to get extra vaccine to combat surge; Regeneron cocktail protects from infection: Live COVID-19 updates",
                       "Hillary Clinton on Iran: We need “patient, persistent diplomacy with people who are not our friends”",
                       "Opinion: Biden wants to make the US more competitive. His tax hikes will do the opposite",
                       "CEOs discuss pulling donations, additional public statements to fight voting bills",
                       "Lockdown eases: How we fit bras at a social distance",
                       "Cardiologist testifies police restraint killed George Floyd",
                       "Cornyn draws criticism for tweet questioning if Biden 'really in charge'",
                       "Prince Philip: A simple, family farewell",
                       "VIDEO: Community Holds Parade 'Fit for a Princess' for Girl Diagnosed with Cancer",
                       "Covid: Restaurants and pubs have reopened, but what are the rules?",
                       "Prince Philip: How the Royal Navy shaped the Duke of Edinburgh",
                       "See huge water tornado approach buildings on beach shore",
                       "Amid Covid, this popular Mexican restaurant  serves up social justice issues too",
                       "Rory McIlroy Attacked By Mother Hawk Protecting Golf Ball That Bounced Into Nest",
                       "From William and Harry, Loving but Separate Tributes to Prince Philip",
                       "Report: Facebook Has Ignored 'Politically Manipulative Behavior' by Third-World Dictators and Politicians",
                       "NC Lawmakers Move to Protect Youth from Transgender Drugs, Surgeries",
                       "23 killed in West African terror attack",
                       "Marco Rubio hammers Obama over Iran prisoner swap",
                       "Prince Philip: Duke's support for Aberfan families remembered",
                       "Will Smith movie 'Emancipation' abandons Georgia over voting restrictions",
                       "Uber Posts Record Demand for March",
                       "Biden’s CBP nominee defended sanctuary cities, criticized police",
                       "Kansas City Chiefs' Britt Reid was allegedly intoxicated, traveling 84 mph before car crash that injured girl",
                       "Maryland becomes first state to repeal police bill of rights, overriding Hogan veto"]
